export default {
  FIREBASE_APP_API_KEY: 'AIzaSyBGxx0yb6R4b6jTFWaBt_Tkft7SL9bwPJA',
  // FIREBASE_APP_AUTH_DOMAIN: '[YOUR CONFIG HERE]',
  // FIREBASE_APP_DATABASE_URL: '[YOUR CONFIG HERE]',
  FIREBASE_APP_PROJECT_ID: 'class19-fp-webshop',
  // FIREBASE_APP_STORAGE_BUCKET: '[YOUR CONFIG HERE]',
  // FIREBASE_APP_MESSAGING_SENDER_ID: '[YOUR CONFIG HERE]',
  // FIREBASE_APP_ID: '[YOUR CONFIG HERE]',
};
