exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('users')
    .del()
    .then(() =>
      // Inserts seed entries
      knex('users').insert([
        {
          uid: '2r49MqKfRNVUIcOOLPt9psmLYdi1',
          full_name: 'Test User1',
          email: 'test33@3.com',
          address: 'test address 1',
          mobile: '55223322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'COzFOvsO89X4x5RdRRVWoIIrqSo1',
          full_name: 'Test User2',
          email: 'testuser@0309.com',
          address: 'test address 2',
          mobile: '55223323',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'EGG1VfsbUxRVBSuwJOKhJFesk8H3',
          full_name: 'Test User3',
          email: 'sattest@sat.com',
          address: 'test address 3',
          mobile: '34522332',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'M8a2PB5qeISLegP11BBIblGtc8m2',
          full_name: 'Test User4',
          email: 'manu@hail.com',
          address: 'test address 4',
          mobile: '12353322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'QsZkAedqMtQqzmroSbepMVItWcD2',
          full_name: 'Test User5',
          email: 'ula@gil.com',
          address: 'test address 5',
          mobile: '12223322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'Y2Xp4nTaBAOsuF7qNF28l0wMHPh1',
          full_name: 'Test User6',
          email: 'test@t.com',
          address: 'test address 6',
          mobile: '44523322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'V4N82jkT41SBZ3eJLUQmFuPkS5B3',
          full_name: 'Test User7',
          email: 'gh@kl.com',
          address: 'test address 7',
          mobile: '76822332',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'UZT9cILzlZN7futPPsgbY7nK7p32',
          full_name: 'Test User8',
          email: 'hrv@gl.com',
          address: 'test address 8',
          mobile: '53523362',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: 'U5Y1mDsFgQhVuslWonSPRdB1Fkk1',
          full_name: 'Test User9',
          email: 'div@t.com',
          address: 'test address 9',
          mobile: '93223322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          uid: '0kjx3QQk50ZZ4A593Kf0Wg5LgYr1',
          full_name: 'Test User10',
          email: 'div@test.com',
          address: 'test address 10',
          mobile: '9234322',
          zipcode: '1234',
          city: 'Test City',
          country: 'Test Country',
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
      ]),
    )
    .catch((error) => {
      console.error(error);
    });
};
